version: '3.9'

services:
  django:
    build: ./django-api-portfolio
    command: bash -c "sleep 10 && python manage.py makemigrations && python manage.py migrate && gunicorn mysite.wsgi -c /deploy/gunicorn/gunicorn_config.py"
    volumes:
      - ./django-api-portfolio:/backend
      - ./deploy/gunicorn/gunicorn_config.py:/deploy/gunicorn/gunicorn_config.py
    expose:
      - 8000
    depends_on:
      - postgres

  nginx:
    build: ./deploy/nginx
    volumes:
      - ./deploy/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./public/static:/public/static
      - ./public/media:/public/media
      - backend:/backend
    ports:
      - 80:80
    depends_on:
      - django
      - postgres


  postgres:
    image: postgres:12.2
    volumes:
      - postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - 5432:5432

volumes:
  backend:
  postgres:
