version: '3.3'

services:
  nginx:
    build: ./nginx
    volumes:
      - static_volume:/usr/src/app/static
      - media_volume:/usr/src/app/media
    ports:
      - 80:80
    depends_on:
      - web


  web:
    build: 
      context: ./portfolio-web
    command: gunicorn mysite.wsgi:application --bind 10.31.1.74:8000
    ports:
      - 8000:8000
    working_dir: /usr/src/app/
    volumes:
      - ./portfolio-web:/usr/src/app
      - static_volume:/usr/src/app/static
      - media_volume:/usr/src/app/media
    expose:
      - 8000
    depends_on:
      - postgres

  postgres:
    image: postgres:15.2
    volumes:
      - postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - 5432:5432

volumes:
  postgres:
  static_volume:
  media_volume:
